### PR TITLE
Create harbour-yubikey-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Add Swedish translation.
I don't own a YubiKey but I didn't find any great mysteries so here's the translation anyway.

### CODE REVIEW

**Comment by monich** [comment]
Thanks!

**Comment by attah** [comment]
@eson57 It is something about "Tryck på" that feels off when it is about tapping your phone and not the finger to the token.
How about "rör vid" instead? Or even more verbose "håll telefonen/enheten mot"?

**Comment by eson57** [comment]
@attah What string is it about? I might have mistaken something.

**Comment by attah** [comment]
@eson57 All strings where touch has been translated to "tryck på" (i.e. all containing touch in the source translation).

**Comment by eson57** [comment]
Well, I know it's not a perfect translation and I have this problem all the time in many project translations when it comes to tapping/touching. 
As for this project I think it is all about touching the token and not the phone, is it not? I have used "tryck på" in all my translations and we do use the same in Sailfish OS itself. I have of course considered to use "rör vid" but that just gives me questions like, "where should I touch that thing, and how"?
I might be wrong but in my opinion "rör vid" feels even more off, because what you really do, is to press/tap your finger on that token/phone.
Still I can change the translation if you want, as I said earlier, I don't even own a Yubikey.

**Comment by attah** [comment]
> As for this project I think it is all about touching the token and not the phone, is it not?

It is about touching _the phone_ to the token.
In Swedish i don't really consider that similar enough to finger-based touch to use the same terminology.
And that then doesn't really have precedent in regular SFOS translations.
The only real precedent i can think of is Matakortti, which uses "Lägg telefonen mot kortet".
But since laying it down is somewhat irrelevant and even impractical for the action, i guess i suggest "Håll telefonen mot"...  "en YubiKey", "samma YubiKey" etc.

**Comment by eson57** [comment]
Aha, then I did misunderstand. Will fix it asap. Thanks for pointing it out.

**Pull request merged**
